app/models.py
from datetime import datetime 

from . import db

class User(db.Model):
	__tablename__ = "user"
	id = db.Column(db.String(255), primary_key=True, nullable=False)
	username = db.Column(db.String(20), nullable=False)
	ip = db.Column(db.String(20), nullable=False)
	device = db.Column(db.String(20), nullable=False)



class Auth(db.Model):
	__tablename__ = "auth"
	id = db.Column(db.String(255), db.ForeignKey('user.id'), primary_key=True, nullable=False )
	email = db.Column(db.String(20), primary_key=True, nullable=False)
	credentials = db.Column(db.String(1000), nullable=True)

class order(db.Model):
	__tablename__ = "order"
	id = db.Column(db.String(255), db.ForeignKey('user.id'), primary_key=True, nullable=False)
	email = db.Column(db.String(20), primary_key=True, nullable=False)
	last_order = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

login_manager = LoginManager()
bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	login_manager.init_app(app)
	bootstrap.init_app(app)
	db.init_app(app)

	from .main import main as main_blueprint
	app.register_blueprint(main_blueprint)

	from .auth import auth as auth_blueprint
	app.register_blueprint(auth_blueprint)
	
	return app

app/main/__init__.py
from flask import Blueprint

main=Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template
from flask_login import current_user
from . import main

@main.route('/', methods=['GET', 'POST'])
def index():
	return render_template('index.html')

@main.route('/user/<name>')
def user(name):
	return render_template('user.html')

@main.route('/profile')
def profile():
  	pass

@main.route('/setting')
def setting():
	pass



   	  

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Kogo{% endblock%}

{% block head %}
{{ super() }}
{% endblock%}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index')}}">Kogo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index')}}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ current_user.username }}</a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('main.profile') }}">Profile</a></li>
                        <li><a href="{{ url_for('main.setting') }}">Setting</a></li>
                        <li><a href="{{ url_for('auth.signout') }}">Sign Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.signin') }}">Sign In</li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Welcome to Kogo!</h1>    
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/home.html
{% extends "bootstrap/base.html" %}

{% block title %}Kogo{% endblock%}

{% block head %}
{{ super() }}
{% endblock%}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Kogo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="/signin">Sign In</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Welcome to Kogo!</h1>    
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Kogo{% endblock %}

app/templates/user.html
{% extends "bootstrap/base.html" %}

{% block title %}Kogo{% endblock %}

{% block head %}
{{ super() }}
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Kogo</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Welcome to Kogo, {{ name }}</h1>    
</div>
{% endblock %}